apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bar
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bar
    spec:
      affinity:
        podAffinity:
        podAntiAffinity:
      containers:
        - name: baz
          image: busybox
