apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "DotNetCoreDocker.fullname" . }}
  labels:
{{ include "DotNetCoreDocker.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "DotNetCoreDocker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "DotNetCoreDocker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        # runAsUser: 1000
        # runAsGroup: 1000
        # fsGroup: 1000
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort:  {{ .Values.containerHttpPort }}
              protocol: TCP  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}          
          env:
          - name: MSG
            value: {{ .Values.msg }}  
